#!/bin/sh

while read -r file
do
    case "$1" in
        "w") feh --bg-scale "$file" & ;;
        "r") convert -rotate 90 "$file" "$file" ;;
	    "R") convert -rotate -90 "$file" "$file" ;;
        "c") printf "%s" "$file" | xclip -sel clip ;;
        "C") xclip -selection clipboard "$file" -t image/png ;;
        "i") notify-send "File information" "$(mediainfo "$file")" ;;
    esac
done
